name: Auto-update wowsims submodule

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive

      - name: Update wowsims submodule
        run: |
          git submodule update --init --recursive

          cd vendor/wowsims-mop
          git fetch origin master
          git checkout -B master origin/master
          git reset --hard origin/master

      - name: Create pull request if changed
        id: create-pull-request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          add-paths: |
            vendor/wowsims-mop
            .gitmodules
          commit-message: "chore: auto-update wowsims/mop submodule"
          branch: chore/auto-update-wowsims-submodule
          delete-branch: true
          title: "chore: auto-update wowsims/mop submodule"
          body: |
            Automated submodule update for `vendor/wowsims-mop`.

            This PR was created by the scheduled submodule update workflow.
          labels: |
            dependencies

      - name: Enable auto-merge for PR
        if: ${{ steps.create-pull-request.outputs.pull-request-number }}
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.create-pull-request.outputs.pull-request-number }}
          merge-method: squash